name: Build steerd
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: steerd
      - name: Install dependencies
        run: sudo apt install git subversion build-essential python gawk unzip libncurses5-dev zlib1g-dev libssl-dev wget time libncurses-dev
      - name: Download OpenWrt SDK
        run: curl -o openwrt-sdk.tar.xz https://downloads.openwrt.org/snapshots/targets/ath79/generic/openwrt-sdk-ath79-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz
      - name: Extract OpenWrt SDK
        run: tar xf openwrt-sdk.tar.xz && mv openwrt-sdk-ath79-generic_gcc-8.4.0_musl.Linux-x86_64 sdk
      - name: Create config
        run: make -C sdk defconfig && echo "CONFIG_SRC_TREE_OVERRIDE=y" >> sdk/.config
      - name: Update package feed
        run: ./sdk/scripts/feeds update {base,packages}
      - name: Add steerd package to package feed
        run: mkdir $GITHUB_WORKSPACE/sdk/feeds/packages/net/steerd && cp -r $GITHUB_WORKSPACE/steerd/contrib/openwrt/. $GITHUB_WORKSPACE/sdk/feeds/packages/net/steerd/
      - name: Link steerd source code
        run: ln -s $GITHUB_WORKSPACE/steerd/.git $GITHUB_WORKSPACE/sdk/feeds/packages/net/steerd/git-src
      - name: Install package feeds
        run: ./sdk/scripts/feeds update -i && ./sdk/scripts/feeds install -a
      - name: Compile steerd
        run: make -C sdk package/steerd/{clean,compile} V=s
      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: sdk/bin/packages/mips_24kc/packages
 